on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: riotcoding.lima-ftp.de
        username: riotcoding
        password: ${{ secrets.FTP_PASS }}
        server-dir: ./test/
        local-dir: ./particle-storm/
        
    - name: 📂 Sync files 2
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: riotcoding.lima-ftp.de
        username: riotcoding
        password: ${{ secrets.FTP_PASS }}
        server-dir: ./test-lorem/
        local-dir: ./wallpaper-finder/
